version: '3.8'

services:
  mysql-container:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    environment:
      DB_CONNECTION_STRING: "mysql+pymysql://your_user:your_password@mysql-container/testdb"
    networks:
      - my_network
    ports:
      - "8000:8000"
    depends_on:
      mysql-container:
        condition: service_healthy

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: